### ISSUE TITLE
Fargate Task definition memory parameters

### ISSUE THREAD

**Issue by w601sxs** [awsdocs/aws-cdk-guide#145]
Currently memory in the main Task definition is a string but memory limit is an int / float. Can this be consistent? Any strong reason to do this?

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs/TaskDefinition.html

**Comment by Jerry-AWS** [comment]
Hi @w601sxs. Thanks for taking the time to create this issue! 

However, I'm closing it because it isn't really an issue with the AWS CDK Developer Guide. I would transfer the issue to the right place for you, but that repo is in a different GitHub organization and GitHub doesn't support moving issues to a repo in a different organization.

I suggest you open it again over at https://github.com/aws/aws-cdk/issues.
