### ISSUE TITLE
Fargate Service enable_cloud_map 

### ISSUE THREAD

**Issue by w601sxs** [awsdocs/aws-cdk-guide#146]
I did

workerService = ecs.FargateService(self, ...,...,..,)
workerService.enable_cloud_map(..,.,)

For which I got the following error

'FargateService' object has no attribute 'enable_cloud_map'

It looks like it is available in the docs as a method https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs/FargateService.html

**Comment by Jerry-AWS** [comment]
Hi @w601sxs. Thanks for taking the time to create this issue! 

However, I'm closing it because it isn't really an issue with the AWS CDK Developer Guide. I would transfer the issue to the right place for you, but that repo is in a different GitHub organization and GitHub doesn't support moving issues to a repo in a different organization.

I suggest you open it again over at https://github.com/aws/aws-cdk/issues.
