### ISSUE TITLE
Construct prop defaultArguments? accepts only JSON in AWS Glue

### ISSUE THREAD

**Issue by prabhacloud** [awsdocs/aws-cdk-guide#251]
CDK Guide says you can pass any type to ` defaultArguments?`  when you are creating/updating a Glue job. But when tried passing a string as shown below it throws an error **_Error: Resolution error: Supplied properties not correct for "CfnJobProps" defaultArguments: "--job-bookmark-option: job-bookmark-enable" should be an 'object'._** 

` default_arguments=str("--job-bookmark-option: job-bookmark-enable")`  -- doesn't work

But when an object type is passed it works as expected and also [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html) doc says the type for DefaultArguments is JSON.

`default_arguments={ '--job-bookmark-option': 'job-bookmark-enable' }`  -- works fine

**Comment by Jerry-AWS** [comment]
@prabhacloud Could you file this over at the [CDK GitHub repo](https://github.com/aws/aws-cdk/issues)? This looks like an API Reference issue, or possibly a bug in how the argument's type is specified in the construct (since the API reference is generated from those). This repo is only for the CDK Developer Guide.

**Comment by Jerry-AWS** [comment]
I've reposted this over at the CDK repo. https://github.com/aws/aws-cdk/issues/9781
