### ISSUE TITLE
CDK docs could be clearer about Node.js dependency

### ISSUE THREAD

**Issue by mikeblas** [awsdocs/aws-cdk-guide#291]
The AWS CDK "getting started" topic could be a bit clearer about its NodeJS dependency. This page: https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html has this to say:

> All CDK developers need to install Node.js 10.3.0 or later, even those working in languages other than TypeScript or JavaScript. The AWS CDK Toolkit (cdk command-line tool) and the AWS Construct Library run on Node.js. The bindings for other supported languages use this back end and tool set. We suggest the latest LTS version.

> Important
> Node.js versions 13.0.0 through 13.6.0 are not compatible with the AWS CDK.

It seems that 10.3 is required at a minimum, but it's not completely clear if versions newer than 13.6 _are_ compatible. It's also not clear which version is "the latest LTS version".  The [NodeJS documentation](https://nodejs.org/en/about/releases/) implies that only builds with even version numbers are candidates for being an LTS version, but it's not clear that the "latest" version is LTS yet or not. At this moment, the NodeJS website descries v16 as a "candidate".

To help customers maintain compatibility with whatever else is happening in their tooling or development environment, it seems like this documentation could be clarified. Maybe something more like this:

> The AWS CDK Toolkit (cdk command-line tool) and the AWS Construct Library run on Node.js. The CDK Toolkit itself requires Node.js, even if generating code and projects for languages other than TypeScript or JavaScript.

> The toolkit requires Node.js version 10.3.0 or later at a minimum. It is not compatible with versions 13.0.0 through 13.6.0, but will work with later versions. We suggest the latest LTS version candidate, which at the time of this writing is v16.

The point is to consolidate the compatible versions and clarify the runtime requirements. Using specific version number (rather than "latest") further reduces ambiguity.

**Comment by Jerry-AWS** [comment]
From https://github.com/awsdocs/aws-cdk-guide/issues/292

The CDK Workshop says that any Node.js version greater than or equal to 10.3.0 will work:

https://cdkworkshop.com/15-prerequisites/300-nodejs.html

Other documentation contradicts that. For example, this page has a "Prerequisites" section:

**Comment by Jerry-AWS** [comment]
@mikeblas Because Node.js intends to be backward-compatible (as does JavaScript itself), "the latest" is generally an appropriate recommendation. (An exception being a few specific 13.0.x versions.) The current 10.13 minimum is set primarily by TypeScript, which doesn't use any JavaScript language features that require later versions of Node.j.s. Other Node.js improvements from version to version don't much affect the CDK.

That said, our recommendation did get a little out of sync and outdated. The [CDK repo's README](https://github.com/aws/aws-cdk/blob/master/README.md) is canonical since it's updated by the developers. I've updated the Developer Guide to synchronize with that guidance. 

I've also added a PR to update the CDK Workshop. https://github.com/aws-samples/aws-cdk-intro-workshop/pull/199
