### ISSUE TITLE
Committing context to version control conflicts with multi stage environments

### ISSUE THREAD

**Issue by ukautz** [awsdocs/aws-cdk-guide#315]
Regarding the [recommendation](https://github.com/awsdocs/aws-cdk-guide/blame/main/doc_source/context.md#L19) to commit the `cdk.context.json` into version control in the context of multi-stage environments.

Here the **use case**:

When continuously developing a service that is "live" and has production load then additional deployments of that service are needed, that
- match the production setup as close as possible
- do not affect the production service i.e. do not share resources with the production service.

This allows for experiments with new features or run load/stress tests or [a host of other useful things](https://en.wikipedia.org/wiki/Deployment_environment#Environments).

Now to the **issue**:

Following the recommendation to commit `cdk.context.json` to version control (that also contains the code that describes the infrastructure) tightly couples the whole repository to a specific stage.
 

- - - 

There are of course many ways around it, but non without cost:

- Having one code repository per stage - *cost*: risking divergence in between stages, creating unnecessary redundancies, not following d.r.y.
- Renaming the `cdk.context.json` to `cdk.<stage-name>.context.json` (or so) within the code repository and then undoing that in during deployment (in the CI/CD pipeline) - *cost*: not following recommendation, adding complexity, introducing surprises
  - Extending the appropriate `cdk` commands, so that the path to `cdk.context.json` can be specified or provided via environment variable - *cost*: effort
- Not committing `cdk.context.json` to version control at all, but always executing `cdk boostrap` - *cost*: not following recommendation, risking inconsistent setup(?)
- ..

- - -

I think it would be really helpful if you could elaborate on that use-case in your recommendation, as the above multi-stage scenario is quite often (mostly?) considered best practice itself.

**Comment by Jerry-AWS** [comment]
For reference, here's the original PR that added this guidance to the API Reference: https://github.com/aws/aws-cdk/pull/12565

That guidance was specifically about VPC lookups.  The Developer Guide guidance I wrote was more general, since obviously you can't commit *only* the cached VPC lookups in `cdk.context.json`. (I did add a mention to the Resources topic where `fromLookup()` is mentioned specifically.)

@rix0rrr?

**Comment by rix0rrr** [comment]
`cdk.context.json` is a cache for all nondeterministic decisions your program has made from deployment-to-deployment, and is necessary to keep generated infra consistent. I would *definitely* recommend you check it in.

Personally, I would say you don't even need to worry about keeping the `cdk.context.json` of various deployments separate:

* First of all, we recommend you model all of your deployments in one CDK app; then selectively deploy from the available set of all deployments. In that case, `cdk.context.json` will naturally contain a superset of all lookup data for all stages.
* In general the `cdk.context.json` does not contain resources that are part of the application itself, so there's no downside. Vpcs might qualify but they are generally in there because people don't want to deploy them as part of the CDK app but consider them part of the "environment", and are immutable.

If you MUST have different values for the same context key for different deployments (why?) then you could always have a single repository with different directories, one per deployment, that all deploy the same CDK app against a different `cdk.context.json`... or have multiple apps each with their own `cdk.context.json`, that all deploy the same `Construct` (which is in the same repo).

I would definitely not go copy/pasting code around.

**Comment by Jerry-AWS** [comment]
If you absolutely need a different context value, you can always use the `--context` option on a given `cdk synth` or `cdk deploy` command to override value(s) in `cdk.context.json`.

Perhaps it'd be nice to have a `--context-cache my-context.json` option so you could specify an entirely separate context file to be used. If that would be useful to you, I encourage you to request it over at the CDK repo: https://github.com/aws/aws-cdk/issues/new?assignees=&labels=feature-request%2C+needs-triage&template=feature-request.md&title=%28module+name%29%3A+short+issue+description

I'm going to close this now since I don't think it's an issue with the CDK Developer Guide. Feel free to reopen if you have further comments.

**Comment by ukautz** [comment]
Thank you both! I am glad to hear that unintentional collisions/conflicts of context keys are not possible, even with a shared `cdk.context.json` in the multiple stage scenario I described.

This has clarified a lot form me how context is to be used. I hope the next person with the same confusion will find this thread equally helpful :+1: 

> If you MUST have different values for the same context key for different deployments (why?) 

Only for scenarios similar to what is described in [this example here](https://docs.aws.amazon.com/cdk/latest/guide/get_context_var.html), or more specific: command line injected context that differentiates the stages (`-c domain=dev.acme.tld` vs `-c domain=pro.acme.tld` etc).

> I would definitely not go copy/pasting code around.

Words to live by :wink:
