### ISSUE TITLE
Previous version documentation is not available

### ISSUE THREAD

**Issue by aherrmann13** [awsdocs/aws-cdk-guide#387]
Can you publish documentation for past versions of the library?  I have a project that is on version `1.72.0` and while I can upgrade it I would like to see the documentation for this version.

The specific issue I'm running into is I'm trying to hook up DDB to a kinesis stream and I can't find documentation on the props and methods available for this version, and 'upgrade minor version' might work but I would 1) like to at least know what version added this functionality and 2) what functionality exists in my current version

**Comment by Jerry-AWS** [comment]
That's a good suggestion.

It's not something we can easily do for the Developer Guide, but fortunately it's not as important there. You can get old versions of the API Reference from GitHub releases. [This issue](https://github.com/aws/aws-cdk/issues/8083) has more details on doing that (though the experience could stand some improvement).

This is something that's definitely on our radar, though. I'm going to close this issue since it's not something we can do with the Developer Guide in the foreseeable future, but please do comment on the issue I linked or else create a new one if it doesn't really cover your use case. (API Reference issues belong in the main CDK repo.)
